export const driverState = {
  driver_data: {
    usdot: "",
    email: "",
    business_name: "",
    phone: "",
    start_date: "",
    name: "",
    extra_driver: "",
  },
  truck_data: {
    year: "",
    make: "",
    vin: "",
    unit: "",
    plate_number: "",
    plate_issue_state: "",
    is_opportioned: "",
    registered_weight: "",
    axles: "",
    commodity: "",
    is_leased: "",
    leasing_company: "",
    usdot: "",
  },
  route_data: {
    entrance_point: "",
    exit_point: "",
    stop_locations: "",
    miles: "",
    total_amount: "",
    trip_type: "",
    trip_method:"",
    type: "",
    usdot: "",
  },
};
